### ISSUE TITLE
Why is it deprecated ?

### ISSUE THREAD

**Issue by Luke1962** [rockchip-linux/gstreamer-rockchip-extra#20]
Why is it deprecated ?
In which relation it is w.r.t [gstreamer-rockchip](https://github.com/rockchip-linux/gstreamer-rockchip)? are they mutually exclusive or independent ?
Thank you

**Comment by JeffyCN** [comment]
Currently this is no longer supported by rockchip.
It provides 4 plugins:
1/ kmssink <--- we are patching the official one directly now
2/ rkcamsrc <---- we are using rockchip camera engine(remote 3A and official v4l2src) now
3/ rgaconvert <---- we are using linux-rga(librga) now
4/ rkximagesink <---- it's in gstreamer-rockchip now
